### ISSUE TITLE
ITextRenderer class, but no dependency on IText

### ISSUE THREAD

**Issue by kimherter** [flyingsaucerproject/flyingsaucer#296]
In some places, class names contain "iText" (e.g. ITextRenderer), although there seem to be no dependencies on iText. Is this a purely historical origin? Regarding licenses, this is a bit confusing.

**Comment by pbrant** [comment]
I suppose it is semi-historical. Flying Saucer now uses OpenPDF which is a fork of the last MPL/GPL licensed version of iText. It is, however, for all intents and purposes iText though.

Note too there is a fork of Flying Saucer that uses PDFBox instead of iText along with some other enhancements. Development seems to have stalled there though. We've never had any contact with the developers so I can't recommend it one way or the other.
