### ISSUE TITLE
Remove JSR305 dependency

### ISSUE THREAD

**Issue by kwin** [flyingsaucerproject/flyingsaucer#404]
JSR305 is dormant since more than 14 years now (https://groups.google.com/g/jsr-305/c/4vqYTAuWncY and https://jcp.org/en/jsr/detail?id=305).

Please switch to an alternative null annotation library due to the split-package issue in https://nipafx.dev/jsr-305-java-9/ and some other minor issues. Examples are: 

1. https://www.jetbrains.com/help/idea/annotating-source-code.html,
2. https://jakarta.ee/specifications/annotations/2.1/apidocs/jakarta.annotation/jakarta/annotation/package-summary or
3. https://jspecify.dev/

The last option probably being the most future-safe option, although tool support lacks a bit yet.

**Comment by asolntsev** [comment]
I know that JSR305 is dormant, but it's still supported by IDEA and other tools, so I personally don't have any problems with it. ;)

Yes, the "split-package" is a problem, but I personally still don't see any reasons to use Java modules (except for building a minimal JRE for running in docker). And I don't use Java modules in any projects. :)

But ok, no problems, we can replace JSR305 by JetBrains annotations. 
It's the only possible option because both jakarta.ee and JSpecify have only `@Nonnull` and `@Nullable`, and are missing few very useful annotations like `@CheckReturnValue`.

**Comment by cpovirk** [comment]
Hi, I'm just poking my head into random threads related to JSpecify :)

- JSpecify indeed lacks `@CheckReturnValue` at the moment. We [hope to change that](https://github.com/jspecify/jspecify/issues/200), but I don't want to take even public guesses about when a cross-company initiative will get to a given feature :) As an alternative source of a `@CheckReturnValue` annotation in the meantime, I personally like [Error Prone's annotations](https://javadoc.io/doc/com.google.errorprone/error_prone_annotations/latest/allclasses-index.html). Your views on that will likely depend on how many of the other annotations would be useful in your case. (You might also find that the tools you care about support any annotation with the simple class name "CheckReturnValue," in which case you could consider using your own, perhaps declaring package-private versions where necessary if you want to keep it out of your public API.)
- As a successor to `@ParametersAreNonnullByDefault`, we offer [`@NullMarked`](https://jspecify.dev/docs/api/org/jspecify/annotations/NullMarked.html), which you can think of as a generalization of that that also covers fields, return types, and generics in various ways. You can read [more about it and about migration from JSR305 in general in our docs](https://jspecify.dev/docs/using/#if-your-code-already-uses-jsr-305-annotations).
- As those docs suggest, we are still working to make JSpecify the clear right answer for everyone. We're seeing adoption among some projects whose itches it scratches, but you may or may not find yourself in that category anytime soon.
- One thing to watch for with the JetBrains annotations: Because they have [`@Target(METHOD, ..., TYPE_USE)`](https://github.com/JetBrains/java-annotations/blob/4f1401ae7974623303c9db16d62f239eef9110ac/src/jvmMain/java/org/jetbrains/annotations/Nullable.java#L50), it's not possible to annotate arrays correctly in some cases because `@Nullable T[]` means "a nullable array of nullable elements," with no way to say that _only_ the elements are nullable. That's a bit of an edge case, which may or may not apply to any of your APIs.

**Comment by asolntsev** [comment]
@cpovirk Thank you for sharing the knowledge.
Yes, I like the idea of JSpecify, and I hope to migrate to it in near future. 

1. But the lack of `@CheckReturnValue` seems critical to me. I will check ErrorProne, thanks for the hint.
2. In fact, `@NullMarked` is even better than `@ParametersAreNonnullByDefault` because it marks everything non-nullable, not only parameters.
3. In case of JetBrains annotations, IDEA suggests  a workaround for arrays:

```java
    public byte @Nullable [] getBinaryResource(String uri) {
```

**Comment by asolntsev** [comment]
@kwin Could you please test https://oss.sonatype.org/content/repositories/snapshots/org/xhtmlrenderer/flying-saucer-swt-examples/9.10.0-SNAPSHOT/maven-metadata.xml - does it work now (where jsr305 was replaced by JSpecify)?

**Comment by asolntsev** [comment]
implemented in https://github.com/flyingsaucerproject/flyingsaucer/pull/407
